
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author pooja
 */
 class item_p extends javax.swing.JPanel {

   
     front_page1 dis;
     backend obj;
     display_items diobj;
     URL url;
   ImageIcon img;
   BufferedImage img1;
   String product_name;
    item_p()
   {
       
   }
    item_p(front_page1 fpobj,String str) throws Exception{
        
        dis=fpobj;
        product_name=str;
        obj=new backend();
        diobj=new display_items();
        dis.main_panel.removeAll();
        dis.main_panel.setLayout(null);
        dis.main_panel.setBackground(Color.white);
        obj.get_productdetails(product_name);
        obj.get_customerdetails();
       // get_productdetails();
        initComponents();
        
    }
    private boolean verify_pincode()
    {
        String str=jFormattedTextField2.getText();
        int i=0;
          if(str.isEmpty()||jFormattedTextField2.getText().length()!=6){
               JOptionPane.showMessageDialog(dis.main_panel, "Invalid pincode", "Alert", JOptionPane.WARNING_MESSAGE);
               return false;   
           }
       while(i<jFormattedTextField2.getText().length())
       {
           if(Character.isDigit(jFormattedTextField2.getText().charAt(i)))
           {
             
           }
       
           else{
               JOptionPane.showMessageDialog(dis.main_panel, "Invalid pincode", "Alert", JOptionPane.WARNING_MESSAGE);
               return false;      
           }
           i++;
       }
       return true;
    }
    private ImageIcon display_img() throws Exception
    {
       try {
            url = null;
           try {
               url = new URL(obj.product_image);
           } catch (MalformedURLException ex) {
               Logger.getLogger(display_items.class.getName()).log(Level.SEVERE, null, ex);
           } catch (Exception ex) {
               Logger.getLogger(display_items.class.getName()).log(Level.SEVERE, null, ex);
           }
            img1 = ImageIO.read(url);
            img = new ImageIcon(img1);
            // System.out.println(obj.rs.getString("product_image"));
            //Image si=img.getImage();
            //Image new_img=si.getScaledInstance(250,450,Image.SCALE_SMOOTH);
            //img =new ImageIcon(si);
   
       } catch (IOException ex) {
           Logger.getLogger(display_items.class.getName()).log(Level.SEVERE, null, ex);
       }
       return img;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel("",JLabel.CENTER);
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel( "",SwingConstants.CENTER);
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("jLabel1");

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setText("BUY NOW");

        jFormattedTextField1.setText("enter pincode");

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setText("ADD TO CART");

        jLabel2.setText("Delivery");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        //jButton3.setText("",JLabel.CENTER);

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel3.setBackground(new java.awt.Color(204, 0, 0));
         try {
            jLabel3.setIcon(display_img());
         } catch (Exception ex) {
             Logger.getLogger(item_p.class.getName()).log(Level.SEVERE, null, ex);
         }
        //jLabel3.setIcon(display_img());

        jLabel3.setOpaque(false);
        dis.main_panel.add(jLabel3);
        jLabel3.setBounds(10, 10, 440, 605);

        jButton4.setText("ADD TO CART");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
       dis.main_panel. add(jButton4);
        jButton4.setBounds(850, 540, 210, 40);

        jButton5.setText("BUY NOW");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        dis.main_panel.add(jButton5);
        jButton5.setBounds(630, 540, 220, 40);

        jFormattedTextField2.setText(String.valueOf(obj.pincode));
        dis.main_panel.add(jFormattedTextField2);
        jFormattedTextField2.setBounds(730,430, 150, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("   Delivery");
        dis.main_panel.add(jLabel4);
        jLabel4.setBounds(630, 430, 90, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText(obj.product_name);
        dis.main_panel.add(jLabel5);
        jLabel5.setBounds(640, 20, 430, 50);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText(" ₹"+obj.product_price);
        dis.main_panel.add(jLabel6);
        jLabel6.setBounds(640, 100, 120, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Product Description");
        dis.main_panel.add(jLabel7);
        jLabel7.setBounds(640, 180, 190, 30);

        jLabel8.setForeground(new java.awt.Color(204, 51, 0));
        jLabel8.setText(obj.product_desc);
        jLabel8.setOpaque(true);
        dis.main_panel.add(jLabel8);
        jLabel8.setBounds(640,180, 380, 230);

        jLabel9.setText("");
        dis.main_panel.add(jLabel9);
        jLabel9.setBounds(1120, 350, 80, 20);

        jLabel10.setText("CHANGE");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        dis.main_panel.add(jLabel10);
        jLabel10.setBounds(920, 430, 80, 30);
    }// </editor-fold>                        
   
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        //order_panel obj=new order_panel(dis);
        //dis.main_panel.revalidate();
        boolean val =verify_pincode();
        if (val==true)
        {
           order_panel obj=new order_panel(dis);
           dis.main_panel.revalidate();
        }
        System.out.println("hii done ");
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // ADD TO CART
        
         boolean val =verify_pincode();
        if (val==true)
        {
           add_to_cart  atc=new add_to_cart(dis);
           dis.main_panel.revalidate();
        }
        System.out.println("hii done ");
    }                                        

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {                                      
        //CHANGE PINCODE
    }                                     


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
