/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author pooja
 */
//public class item_p extends javax.swing.JPanel {

    /**
     * Creates new form cart
     */front_page1 dis;
   // public item_p(front_page1 fpobj) {
        dis=fpobj;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("jLabel1");

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setText("BUY NOW");

        jFormattedTextField1.setText("enter pincode");

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setText("ADD TO CART");

        jLabel2.setText("Delivery");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton3.setText("jButton3");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel3.setBackground(new java.awt.Color(204, 0, 0));

        jLabel3.setText("jLabel3");

        jLabel3.setOpaque(true);
        add(jLabel3);
        jLabel3.setBounds(30, 20, 440, 510);

        jButton4.setText("ADD TO CART");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(30, 540, 210, 40);

        jButton5.setText("BUY NOW");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5);
        jButton5.setBounds(260, 540, 220, 40);

        jFormattedTextField2.setText("jFormattedTextField2");
        add(jFormattedTextField2);
        jFormattedTextField2.setBounds(750, 540, 150, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("   Delivery");
        add(jLabel4);
        jLabel4.setBounds(630, 540, 90, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("product name");
        add(jLabel5);
        jLabel5.setBounds(640, 40, 430, 50);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("price");
        add(jLabel6);
        jLabel6.setBounds(640, 160, 120, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Product Description");
        add(jLabel7);
        jLabel7.setBounds(640, 210, 190, 30);

        jLabel8.setForeground(new java.awt.Color(204, 51, 0));
        jLabel8.setText("ABOUT THE PRODEUCT");
        jLabel8.setOpaque(true);
        add(jLabel8);
        jLabel8.setBounds(640, 260, 380, 230);

        jLabel9.setText("jLabel9");
        add(jLabel9);
        jLabel9.setBounds(1120, 350, 80, 20);

        jLabel10.setText("CHANGE");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        add(jLabel10);
        jLabel10.setBounds(920, 540, 80, 30);
    }// </editor-fold>                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // BUY BUTTON
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // ADD TO CART
    }                                        

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {                                      
        //CHANGE PINCODE
    }                                     


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
