package ams;

import java.awt.*;
import javax.swing.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Random;

public class NewStudent extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationForm
     */
    Connection con;
    PreparedStatement pst;

    public NewStudent() {
        initComponents();
        initialize();
        con = JavaDatabase.ConnectToDB();
        Random();
        Time();
    }

    private void initialize() {
        setTitle("New Student");
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setSize(900, 600);
        setVisible(true);
    }

    public final void Random() {
        Random rd = new Random();
        tfStudentId.setText("" + rd.nextInt(1000 + 1));
    }

    public final void Time() {

        java.util.Date dNow = new java.util.Date();
        SimpleDateFormat ft = new SimpleDateFormat("E yyyy.MM.dd");
        tfJoiningDate.setText("" + ft.format(dNow));
    }

    public void Student() {

        String sql = "INSERT INTO student(Student_ID,Name,Father_Name,Batch_ID,Joining_Date) VALUES(?,?,?,?,?)";
        try {
            pst = con.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(tfStudentId.getText()));
            pst.setString(2, tfName.getText());
            pst.setString(3, tfFatherName.getText());
            pst.setInt(4, Integer.parseInt(tfBatchId.getText()));
            pst.setString(5, tfJoiningDate.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Added New Student");
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void SetAttendence() {
        String sql = "INSERT INTO set_attendance(Student_ID,Name) VALUES(?,?)";
        try {
            pst = con.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(tfStudentId.getText()));
            pst.setString(2, tfName.getText());
            pst.execute();
        } catch (NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackColor = new javax.swing.JPanel();
        lbRegistration = new javax.swing.JLabel();
        lbYourPassword = new javax.swing.JLabel();
        lbAnswer = new javax.swing.JLabel();
        lbYourSecurityQuestion = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbUsername4 = new javax.swing.JLabel();
        tfJoiningDate = new javax.swing.JTextField();
        tfBatchId = new javax.swing.JTextField();
        tfFatherName = new javax.swing.JTextField();
        tfStudentId = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBackColor.setBackground(new java.awt.Color(0, 153, 255));
        panelBackColor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbRegistration.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbRegistration.setText("NEW STUDENT");
        panelBackColor.add(lbRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        getContentPane().add(panelBackColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 100));

        lbYourPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbYourPassword.setText("Joining Date");
        getContentPane().add(lbYourPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        lbAnswer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbAnswer.setText("Batch Id");
        getContentPane().add(lbAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        lbYourSecurityQuestion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbYourSecurityQuestion.setText("Father's Name");
        getContentPane().add(lbYourSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        lbName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbName.setText("Name");
        getContentPane().add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        lbUsername4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbUsername4.setText("Student Id");
        getContentPane().add(lbUsername4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        tfJoiningDate.setEditable(false);
        tfJoiningDate.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfJoiningDate.setToolTipText("");
        tfJoiningDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfJoiningDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJoiningDateActionPerformed(evt);
            }
        });
        getContentPane().add(tfJoiningDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 450, 40));

        tfBatchId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfBatchId.setToolTipText("");
        tfBatchId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfBatchId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBatchIdActionPerformed(evt);
            }
        });
        getContentPane().add(tfBatchId, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 450, 40));

        tfFatherName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfFatherName.setToolTipText("");
        tfFatherName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfFatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFatherNameActionPerformed(evt);
            }
        });
        getContentPane().add(tfFatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 450, 40));

        tfStudentId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfStudentId.setToolTipText("");
        tfStudentId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfStudentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStudentIdActionPerformed(evt);
            }
        });
        getContentPane().add(tfStudentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 450, 40));

        tfName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfName.setToolTipText("");
        tfName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });
        getContentPane().add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 450, 40));

        btnAdd.setBackground(new java.awt.Color(255, 102, 0));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 360, 40));

        btnBack.setBackground(new java.awt.Color(0, 255, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 360, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfJoiningDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJoiningDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJoiningDateActionPerformed

    private void tfBatchIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBatchIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBatchIdActionPerformed

    private void tfFatherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFatherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFatherNameActionPerformed

    private void tfStudentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStudentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStudentIdActionPerformed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Student();
        SetAttendence();
        tfStudentId.setText("");
        tfName.setText("");
        tfFatherName.setText("");
        tfBatchId.setText("");
        tfJoiningDate.setText("");
        tfStudentId.requestFocus();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        dispose();
        ManagementPortal managementPortal = new ManagementPortal();
        managementPortal.show();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lbAnswer;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbRegistration;
    private javax.swing.JLabel lbUsername4;
    private javax.swing.JLabel lbYourPassword;
    private javax.swing.JLabel lbYourSecurityQuestion;
    private javax.swing.JPanel panelBackColor;
    private javax.swing.JTextField tfBatchId;
    private javax.swing.JTextField tfFatherName;
    private javax.swing.JTextField tfJoiningDate;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfStudentId;
    // End of variables declaration//GEN-END:variables
}
